Rh pundit authorization
reherr/industrial-auth-1 pull request #2
Opened 2024-07-16 21:21 UTC by reherr

2024-07-22 20:06 UTC, ajmompr requested changes
Fantastic job; small tweaks to your user policy

2024-07-22 20:06 UTC, ajmompr commented on app/policies/user_policy.rb
> +  def show?
almost! Is your app displaying properly for users who are private. Try moving this logic to a method called show_photos? and setting show to true. Call show_photos? policy in your users#show template

2024-07-22 20:06 UTC, ajmompr commented on app/views/users/show.html.erb
> +<% if policy(@user).show? %>
define a new show_photos? policy method and call it here

2024-07-22 20:06 UTC, ajmompr commented on how?
what is this??

2024-07-23 17:13 UTC, ajmompr approved these changes

2024-07-23 17:13 UTC, ajmompr commented on app/policies/user_policy.rb
> +    user == current_user || !user.private? || user.followers.include?(current_user) || current_user.followers.include?(user)
perf

2024-07-23 17:13 UTC, ajmompr commented on app/views/users/show.html.erb
> +<% if policy(@user).show_photos? %>
perf

2024-07-23 17:24 UTC, borvux approved these changes
everything looks good to me!

2024-07-23 17:24 UTC, borvux commented on app/controllers/application_controller.rb
> +  after_action :verify_policy_scoped, only: :index, unless: :devise_controller?
good job adding for devise

2024-07-23 17:24 UTC, borvux commented on app/policies/user_policy.rb
> +    user == current_user || !user.private? || user.followers.include?(current_user) || current_user.followers.include?(user)
good job doing show_photos to differentiate between show

2024-07-23 17:25 UTC, merged